# Generated by Django 3.0.5 on 2020-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeofuser',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
