# Generated by Django 3.0.5 on 2020-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixer', '0002_auto_20200519_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enroll',
            field=models.IntegerField(default=19111001, unique=True),
            preserve_default=False,
        ),
    ]
