# Generated by Django 3.0.5 on 2020-06-20 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixer', '0002_auto_20200618_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assignee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
