# Generated by Django 3.0.5 on 2020-05-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixer', '0003_user_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acstoken',
            field=models.TextField(default='abcd', max_length=1000),
            preserve_default=False,
        ),
    ]
